### PR TITLE
Team-5 image update

### PR DESCRIPTION
**Pull request by rcj9719**

### CODE REVIEW

**Comment by shehzan10** [comment]
@rcj9719 Thanks for the PR. Please make the following changes:

* Delete team-5.gif and assets/images/projects/team-5.png. These files are not used.
* For the assets/images/projects/team-5.gif, please consider if there is a smaller sized gif that you can submit. The file is almost 11mb and will load very slowly.

**Comment by rcj9719** [comment]
@shehzan10 , noted, will update accordingly. Also, can we add an image and a gif to the page?

**Comment by shehzan10** [comment]
@rcj9719 No, please keep a single image or gif.

**Comment by rcj9719** [comment]
@shehzan10 required changes done.

**Pull request merged**
